{
 "title": "Expenses",
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "year",
    "query": "select year(expenses.date) as year from expenses"
   },
   {
    "name": "month",
    "query": "select month(expenses.date) as __value, monthname(expenses.date) as __text   from expenses order by 1 asc"
   },
   {
    "name": "categories",
    "label": "Categories",
    "query": "select id as __value, name as __text from categories"
   }
  ]
 },
 "panels": [
  {
   "title": "Spending per category",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 14, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(date, \"30d\",0) AS time,\n  sum(price) as \"€\",\n  category_id\nFROM expenses\nWHERE\n  $__timeFilter(date) and category_id in ($categories)\ngroup by 1 ,category_id\nORDER BY date"
    }
   ]
  },
  {
   "title": "Monthly in food ( Food + Deliver)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "yaxes": [
    { "format": "currencyEUR" }
   ],
   "targets": [
    {
     "rawSql": "select expenses.date as time, monthname(expenses.date) as 'metrics', sum(price) as \"€\" from expenses where $__timeFilter(expenses.date) and category_id in ($categories) and month(expenses.date)=8 and year(expenses.date)=$year group by month(expenses.date) order by time asc"
    },
    {
     "rawSql": "select expenses.date as time, monthname(expenses.date) as 'metrics', sum(price) as \"€\" from expenses where $__timeFilter(expenses.date) and category_id in ($categories) and month(expenses.date)=9 and year(expenses.date)=$year group by month(expenses.date) order by time asc"
    },
    {
     "rawSql": "select expenses.date as time, monthname(expenses.date) as 'metrics', sum(price) as \"€\" from expenses where $__timeFilter(expenses.date) and category_id in ($categories) and month(expenses.date)=10 and year(expenses.date)=$year group by month(expenses.date) order by time asc"
    },
    {
     "rawSql": "select expenses.date as time, monthname(expenses.date) as 'metrics', sum(price) as \"€\" from expenses where $__timeFilter(expenses.date) and category_id in ($categories) and month(expenses.date)=11 and year(expenses.date)=$year group by month(expenses.date) order by time asc"
    }
   ]
  },
  {
   "title": "$month expenses",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "select name as \"Category\", sum(price) as \"€\" from expenses join categories on expenses.category_id=categories.id where categories.id not in (\"rent\", \"gifts\", \"cleaning\") and month(expenses.date)=$month and year(expenses.date)=$year group by category_id order by 2 desc;"
    }
   ]
  },
  {
   "title": "Spending per category",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 7, "x": 11, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select now() as time, sum(price) as \"Spended in\", name from expenses left join categories on categories.id=expenses.category_id where category_id!=\"rent\" group by category_id"
    }
   ]
  },
  {
   "title": "Total spend since arrival",
   "type": "stat",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select sum(price) from expenses"
    }
   ]
  }
 ]
}