{
 "title": "Expenses",
 "time": { "from": "now-5y", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "year",
    "query": "select year(expenses.expend_date) as year from expenses"
   },
   {
    "name": "month",
    "query": "select month(expenses.expend_date) as __value, monthname(expenses.expend_date) as __text   from expenses order by 1 asc"
   },
   {
    "name": "categories",
    "label": "Categories",
    "query": "select id as __value, name as __text from categories"
   }
  ]
 },
 "panels": [
  {
   "title": "Last tracked expense",
   "type": "stat",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select CONCAT(DAYNAME(e.expend_date), \" \",DAY(e.expend_date),\",  \",MONTHNAME(e.expend_date),\" \", YEAR(e.expend_date)) as \"Date\" from expenses as e order by expend_date desc limit 1"
    }
   ]
  },
  {
   "title": "Total spend since arrival",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select sum(price) from expenses where category_id in ($categories)"
    }
   ]
  },
  {
   "title": "Average prices on Services",
   "type": "stat",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "select AVG(price), category_id\nfrom expenses\nwhere category_id like \"%Service%\"\nAND  year(expend_date) in ($year) \ngroup by 2\norder by 1"
    }
   ]
  },
  {
   "title": "Acumulated spendings",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "SELECT\n  expend_date,\n  (\n    SELECT\n      SUM(b.price)\n    FROM\n      expenses AS b\n    WHERE\n      b.expend_date <= a.expend_date\n      AND category_id  in ($categories)\n  ) AS \"Acumulation select categories\"\nFROM\n  expenses AS a\nWHERE\n  category_id  in ($categories)\nGROUP BY\n  2\nORDER BY\n  expend_date\nASC;\n"
    }
   ]
  },
  {
   "title": "Expenses table",
   "type": "table",
   "gridPos": { "h": 15, "w": 9, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT e.product AS \"Product\",\n       concat(e.price, \" €\") AS \"Price\",\n       c.name AS \"Category\",\n       e.people AS \"People\",\n       CONCAT(DAYNAME(e.expend_date), \" \", DAY(e.expend_date), \",  \", MONTHNAME(e.expend_date), \" \", YEAR(e.expend_date)) AS \"Date\"\n       FROM expenses AS e\nJOIN categories AS c ON e.category_id=c.id\nWHERE category_id in ($categories) and month(e.expend_date) in ($month) and year(e.expend_date) in ($year) \nORDER BY e.expend_date desc"
    }
   ]
  },
  {
   "title": "Monthly expenses for $year in $categories",
   "type": "graph",
   "gridPos": { "h": 15, "w": 9, "x": 9, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "yaxes": [
    { "format": "currencyEUR" }
   ],
   "targets": [
    {
     "rawSql": "select expend_date as time, monthname(expend_date) as 'metrics', sum(price) as \"€\" from expenses where category_id in ($categories) and month(expend_date)=1 and year(expend_date) in ($year) group by month(expend_date) order by time asc"
    },
    {
     "rawSql": "select expenses.expend_date as time, monthname(expenses.expend_date) as 'metrics', sum(price) as \"€\" from expenses where category_id in ($categories) and month(expenses.expend_date)=2 and year(expenses.expend_date) in ($year) group by month(expenses.expend_date) order by time asc"
    },
    {
     "rawSql": "select expenses.expend_date as time, monthname(expenses.expend_date) as 'metrics', sum(price) as \"€\" from expenses where category_id in ($categories) and month(expenses.expend_date)=3 and year(expenses.expend_date) in ($year) group by month(expenses.expend_date) order by time asc"
    },
    {
     "rawSql": "select expenses.expend_date as time, monthname(expenses.expend_date) as 'metrics', sum(price) as \"€\" from expenses where category_id in ($categories) and month(expenses.expend_date)=4 and year(expenses.expend_date) in ($year) group by month(expenses.expend_date) order by time asc"
    },
    {
     "rawSql": "select expenses.expend_date as time, monthname(expenses.expend_date) as 'metrics', sum(price) as \"€\" from expenses where category_id in ($categories) and month(expenses.expend_date)=5 and year(expenses.expend_date) in ($year) group by month(expenses.expend_date) order by time asc"
    },
    {
     "rawSql": "select expenses.expend_date as time, monthname(expenses.expend_date) as 'metrics', sum(price) as \"€\" from expenses where category_id in ($categories) and month(expenses.expend_date)=6 and year(expenses.expend_date) in ($year) group by month(expenses.expend_date) order by time asc"
    },
    {
     "rawSql": "select expenses.expend_date as time, monthname(expenses.expend_date) as 'metrics', sum(price) as \"€\" from expenses where category_id in ($categories) and month(expenses.expend_date)=7 and year(expenses.expend_date) in ($year) group by month(expenses.expend_date) order by time asc"
    },
    {
     "rawSql": "select expenses.expend_date as time, monthname(expenses.expend_date) as 'metrics', sum(price) as \"€\" from expenses where category_id in ($categories) and month(expenses.expend_date)=8 and year(expenses.expend_date) in ($year) group by month(expenses.expend_date) order by time asc"
    },
    {
     "rawSql": "select expenses.expend_date as time, monthname(expenses.expend_date) as 'metrics', sum(price) as \"€\" from expenses where category_id in ($categories) and month(expenses.expend_date)=9  and year(expenses.expend_date) in ($year) group by month(expenses.expend_date) order by time asc"
    },
    {
     "rawSql": "select expenses.expend_date as time, monthname(expenses.expend_date) as 'metrics', sum(price) as \"€\" from expenses where category_id in ($categories) and month(expenses.expend_date)=10  and year(expenses.expend_date) in ($year) group by month(expenses.expend_date) order by time asc"
    },
    {
     "rawSql": "select expenses.expend_date as time, monthname(expenses.expend_date) as 'metrics', sum(price) as \"€\" from expenses where category_id in ($categories) and month(expenses.expend_date)=11  and year(expenses.expend_date) in ($year) group by month(expenses.expend_date) order by time asc"
    },
    {
     "rawSql": "select expenses.expend_date as time, monthname(expenses.expend_date) as 'metrics', sum(price) as \"€\" from expenses where category_id in ($categories) and month(expenses.expend_date)=12  and year(expenses.expend_date) in ($year) group by month(expenses.expend_date) order by time asc"
    }
   ]
  },
  {
   "title": "Spending per category",
   "type": "piechart",
   "gridPos": { "h": 15, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(price) as \"€\",\n  category_id\nFROM expenses\nWHERE category_id in ($categories) and month(expenses.expend_date) in ($month) and year(expenses.expend_date) in ($year) \nGROUP BY category_id"
    }
   ]
  },
  {
   "title": "$month expenses",
   "type": "barchart",
   "gridPos": { "h": 16, "w": 9, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "select name as \"Category\", sum(price) as \"€\" from expenses join categories on expenses.category_id=categories.id where categories.id not in (\"rent\", \"gifts\", \"cleaning\") and month(expenses.expend_date) in ($month) and year(expenses.expend_date) in ($year) group by category_id order by 2 desc;"
    }
   ]
  },
  {
   "title": "Spending per category",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 9, "x": 9, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(expend_date, \"30d\",0) AS time,\n  sum(price) as \"€\",\n  category_id\nFROM expenses\nWHERE\n  $__timeFilter(expend_date) and category_id in ($categories) and month(expenses.expend_date) in ($month) and year(expenses.expend_date) in ($year) \ngroup by 1 ,category_id\nORDER BY expend_date"
    }
   ]
  },
  {
   "title": "Normal price distribution 0€‎ - 200€‎",
   "type": "histogram",
   "gridPos": { "h": 16, "w": 6, "x": 18, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "select price from expenses where category_id in ($categories) group by price order by 1 desc"
    }
   ]
  },
  {
   "title": "Debug Expenses table",
   "type": "table",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "rawSql": "SELECT e.*, c.name\nFROM expenses AS e\nJOIN categories AS c ON e.category_id=c.id\nWHERE category_id in ($categories)\nORDER BY e.expend_date desc"
    }
   ]
  }
 ]
}