name: Build and Push Docker Image
on:
  release:
    types: [created]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: podman/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: podman/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: podman/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set is_major_bump variable
        id: set_major_bump
        run: |
          version=${{ github.event.release.tag_name }}
          if [[ $version =~ ^[0-9]+\.[0-9]+\.0$ ]]; then
            echo "is_major_bump=true" >> $GITHUB_ENV
          else
            echo "is_major_bump=false" >> $GITHUB_ENV
          fi
      - name: Build and push Container image
        run: |
          version=${{ github.event.release.tag_name }}
          podman push contre95/expense-mate:$version

          # Tag and push the :beta tag
          podman tag contre95/expense-mate:$version contre95/expense-mate:beta
          podman push contre95/expense-mate:beta

          if [[ "${{ github.ref }}" == "refs/heads/main" || "${{ env.is_major_bump }}" == "true" ]]; then
            # Tag and push the :latest tag
            podman tag contre95/expense-mate:$version contre95/expense-mate:latest
            podman push contre95/expense-mate:latest
          fi
