name: Build and Push Podman Image
on:
  workflow_run:
    workflows: ["Tag and Create Release"]
    types: [completed]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman
      - name: Login to DockerHub
        run: |
          podman login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} docker.io
      - name: Set is_major_bump variable
        id: set_major_bump
        run: |
          version=\${{ github.event.release.tag_name }}
          if [[ $version =~ ^[0-9]+\.[0-9]+\.0$ ]]; then
            echo "is_major_bump=true" >> \$GITHUB_ENV
          else
            echo "is_major_bump=false" >> $GITHUB_ENV
          fi
      - name: Build and push Container image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          version=\${{ github.event.release.tag_name }}
          podman build -
