name: Build and Push Docker Image
on:
  release:
    types: [created]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Container image
        run: |
          version=${{ github.event.release.tag_name }}
          docker build --platform linux/amd64,linux/arm64 -t contre95/expense-mate:$version .
          docker push contre95/expense-mate:$version

          if [[ "${{ github.ref }}" == "refs/heads/main" || "${{ env.is_major_bump }}" == "true" ]]; then
            docker build --platform linux/amd64,linux/arm64 -t contre95/expense-mate:latest .
            docker push contre95/expense-mate:latest
          fi
